### ISSUE TITLE
Possibility to override templates from theme folder

### ISSUE THREAD

**Issue by AljosaB** [plastyk/silverstripe-dashboard#118] opened 2019-01-04 13:38 UTC
I'm on SS 4.3 and it seems I can't override templates from my theme. I've copied DashboardPanels.ss and QuickLinksPanel.ss to

/themes/mytheme/templates/DashboardPanels.ss
/themes/mytheme/templates/Plastyk/Dashboard/Panels/QuickLinksPanel.ss

... and made some changes but it's not picking them up. The SS docs (https://docs.silverstripe.org/en/4/developer_guides/templates/themes/) suggest themes are configured like 

```
SilverStripe\View\SSViewer:
  themes:
    - theme_name
    - '$default'
```

I tried adding `SSViewer::set_themes(SSViewer::config()->uninherited('themes'));` line to DashboardAdmin::init and those two templates started to work. Not sure if it's a proper solution.

**Comment by Turnerj** [comment] 2019-01-05 00:20
@3Dgoo , do you remember if we previously looked into overriding the templates from the theme folder?

**Comment by 3Dgoo** [comment] 2019-01-06 10:43
Hi Aljoša,
Thanks for reporting this issue. I'll take a look during the week and see if can work out what's wrong.

@Turnerj no, I don't think I ever tested overriding in the theme directory. I think I only ever tried in mysite or app or dashboard-custom.

**Comment by 3Dgoo** [comment] 2019-01-06 21:14
I just did a quick test here is what I found:
* `DashboardPanels.ss` does work in `app/templates/`
* `DashboardPanels.ss` does work in `dashboard-custom/templates/`
* `DashboardPanels.ss` does not work in `theme/my-theme/templates/`
I'm not sure why though.

**Comment by 3Dgoo** [comment] 2019-01-07 20:32
@AljosaB I have investigated this further and have found that this is an issue with SilverStripe, not just this module.

The issue is these are back end templates, not front end templates. The back end templates do not use the theme templates, therefore we cannot override the back end templates through our theme templates.

I tested this overriding the `SilverStripe/Admin/LeftAndMain.ss` template from SilverStripe Admin module.
The following worked:
`app/templates/SilverStripe/Admin/LeftAndMain.ss`
The following did not work:
`theme/my-theme/templates/SilverStripe/Admin/LeftAndMain.ss`

This makes sense, as the CMS is not using a theme.

So, to override the Dashboard templates you can place the custom templates in either of the following locations:
- `app/templates/`
- `dashboard-custom/templates/`

I hope this helps.

**Comment by AljosaB** [comment] 2019-01-14 09:09
@3Dgoo it's true the theme folder is not used because we're in CMS (admin) but it doesn't mean it can't be added. I already provided you with working example by adding `SSViewer::set_themes(SSViewer::config()->uninherited('themes'));` line to DashboardAdmin::init. By default I think SS calls `SSViewer::set_themes(LeftAndMain::config()->uninherited('admin_themes'));` in LeftAndMain::init which doesn't include user themes but it should be possible to add it to that list?

**Comment by 3Dgoo** [comment] 2019-01-14 09:40
I have submitted a pull request to add functionality that will allow you, or anyone else, to do this through an extension.

This way, theme templates in the Dashboard are not forced upon everyone, but anyone can enable this through an extension.

This is how you would enable it once change #120 is merged in:

```
<?php

use SilverStripe\Core\Extension;
use SilverStripe\View\SSViewer;

class DashboardAdminExtension extends Extension {

    public function updateInit() {
        SSViewer::set_themes(SSViewer::config()->uninherited('themes'));
    }

}
```

```
Plastyk\Dashboard\Admin\DashboardAdmin:
  extensions:
    - DashboardAdminExtension
```

We just need to wait on one of the other module devs to review this change before they merge it in (if they are happy with it).

**Comment by 3Dgoo** [comment] 2019-01-15 02:36
Hi @AljosaB,
This change has now been merged in. Please update your project's copy of the repository and give the above code a try. Let us know if this solves the issue for you.

**Comment by AljosaB** [comment] 2019-01-15 10:44
Thanks @3Dgoo, that will work!

**Closed as completed** 2019-01-15 10:59 UTC
